root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Set the binary output to the correct location for your `main.go` in cmd/
  bin = "./tmp/main"
  
  # Set the Go build command correctly. Since you have `cmd/main.go`, make sure it's building the right file.
  cmd = "go build -o ./tmp/main ./cmd"
  
  # Delay for build completion (milliseconds)
  delay = 1000
  
  # Exclude unnecessary directories and files
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  
  # Additional build settings
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  
  # Polling settings (set to false to avoid polling)
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  
  # Re-run settings
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
 
